# Site settings
name: NLP LAB
email: zhaokangkang0572@outlook.com
author: Zhao Kangkang
url: https://zhaokangkang0572.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/zhaokangkang0572/
baseurl: ""
description: NLP 实验室
meta_description: 赵康康;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

 C:/Ruby22-x64
